name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]  # 监听标签推送（如 v1.0、v2.1.0 等）
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag bank-account-manager:$(date +%s)

    # 登录到Docker Hub（仅在推送时执行，PR 时跳过）
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    # 提取标签信息
    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: iorichina/bank-account-manager
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=sha,format=short
          type=raw,value=latest,enable={{is_default_branch}}  # 仅主分支生成 latest 标签
    
    # 构建并推送镜像（PR 时仅构建不推送，推送事件时才推送）
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}  # PR 不推送，push 事件推送
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
